#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline/promises';
import { stdin as input, stdout as output } from 'process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');
const examplePath = path.join(repoRoot, 'config', 'env.example');

if (!fs.existsSync(examplePath)) {
  console.error('Missing config/env.example. Cannot bootstrap env files.');
  process.exit(1);
}

const raw = fs.readFileSync(examplePath, 'utf8');
const variables = raw
  .split(/\r?\n/)
  .filter((line) => line.trim() && !line.trim().startsWith('#'))
  .map((line) => {
    const [key, ...rest] = line.split('=');
    return { key: key.trim(), defaultValue: rest.join('=').trim() };
  });

const rl = readline.createInterface({ input, output });
console.log('Bootstrapping environment files for backend/frontend/monitoring');
console.log('Press enter to accept defaults. Values are stored only in local .env files.');

const answers = {};
for (const { key, defaultValue } of variables) {
  const prompt = defaultValue ? `${key} [${defaultValue}]: ` : `${key}: `;
  const value = (await rl.question(prompt)).trim();
  answers[key] = value || defaultValue || '';
}

await rl.close();

const header = '# Generated by scripts/bootstrap-env.mjs';
const serialized = `${header}\n${Object.entries(answers)
  .map(([key, value]) => `${key}=${value}`)
  .join('\n')}\n`;

const targets = [
  path.join(repoRoot, 'packages', 'backend', '.env'),
  path.join(repoRoot, 'packages', 'frontend', '.env'),
  path.join(repoRoot, 'packages', 'monitoring', '.env')
];

for (const target of targets) {
  const dir = path.dirname(target);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(target, serialized, 'utf8');
  console.log(`Wrote ${path.relative(repoRoot, target)}`);
}

console.log('Environment bootstrap complete.');
